version:                         '3'
volumes:
    database_data:
services:
  nginx:
    image:                       nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app:/www
  php:
    build:                       ./php
    ports:
      - 9000:9000
    volumes:
      - ../app:/www
    environment:
      - php.extension=intl.so
  db:
        image:                   mariadb:latest
        expose:
            - 3306
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE:      gsb
            MYSQL_USER:          gsb
            MYSQL_PASSWORD:      gsb
  adminer:
          image:   adminer
          ports:
            - 8080:8080
